### ISSUE TITLE
How is it different from `wget`?

### ISSUE THREAD

**Issue by anton-staroverov** [drupal-tome/tome-project#8]
First of all, thanks for the interesting concept! Looks really promising for many use cases.

> If the response was HTML, that HTMl is parsed and assets are collected. The currently recognized assets are pager links (to support Views pagers), images, responsive images (using srcset), stylesheets, scripts, and favicons.
If the response was CSS, URLs within "url(...)" are parsed as assets.
All collected asset paths are then returned to the parent process, which exports them starting at step 3.

This looks more or less the same as how `wget` utility works. What is the big difference?

**Comment by mortenson** [comment]
@tonystar Great question! I should make this into a documentation page on https://tome.fyi, but the main differences are:

1. `wget` cannot determine what pages have been changed, deleted, or added since the last run. Tome uses Drupal cache tags to filter out paths that should not be generated, which (if cache is "warm"), makes it faster than `wget`.
2. `wget` requires an HTTP server to run. Tome uses internal Drupal requests to generate HTML, which has a few benefits:
    1. Multiple pages can be generated in one Drupal bootstrap. This is a performance boost that can have some interesting side-effects (see `\Drupal\tome_static\RequestPreparer`), but is efficient.
    2. You can generate pages for another HTTP host by simply passing `--uri` or inputting one in the user interface. Usually the hostname you're using Drupal on is not going to be the same as the one you host HTML on, so this is a common need.
    3. You can generate HTML on a CI environment without configuring a web server. This is done today on Netlify at https://github.com/drupal-tome/netlify-template
3. `wget` cannot make concurrent requests. Tome can! Not much more to say there.
4. Tome converts Views pagers to work on static hosting, by converting URLs like `/my-view?page=1` to `/my-view/page/1`. This would be fairly difficult with `wget`.
5. Tome copies static assets (CSS, JS, images) with a file copy instead of an HTTP request. This is faster than `wget`.

I hope that helps clear things up!
